### ISSUE TITLE
How can I build the project? (v1.7)

### ISSUE THREAD

**Issue by 587ug9fih** [shinolab/autd3-library-firmware-fpga#3]
Hi, thank you for this useful program.
I have a question.

I'm trying to build the project (v1.7) according to the instruction.
I couldn't find "build.ps1" but there was "clear.ps1".

Should I run "clear.ps1" instead or there is another way to build the project?
Please let me know how to deal with this problem.

Thank you in advance.

**Comment by s5suzuki** [comment]
After generating `init.coe` file by `generate_bram_init_coe.ps1`, open `autd3-fpga.xpr` directly.

**Comment by 587ug9fih** [comment]
Thank you very much.
